version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/lys_db?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=lys_admin
      - SPRING_DATASOURCE_PASSWORD=159
    networks:
      - lys-network
  db:
    image: mysql:8.1.0
    container_name: lys_db
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=lys_db
      - MYSQL_USER=lys_admin
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

networks:
  lys-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
